blog/urls.py
from django.urls import path
from .views import (index, about, add_post,
                    post_list, post_detail, post_edit, post_delete)


app_name = 'blog'
urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('posts/add/', add_post, name='add_post'),
    path('posts/', post_list, name='post_list'),
    path('posts/<slug:slug>/', post_detail, name='post_detail'),
    path('posts/<int:pk>/edit/', post_edit, name='post_edit'),
    path('posts/<int:pk>/delete/', post_delete, name='post_delete'),
]

myblog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from myblog import settings
from blog.views import root

urlpatterns = [
    path('', root),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler403 = "blog.views.forbidden"
handler404 = "blog.views.page_not_found"
handler500 = "blog.views.server_error"

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_detail, change_password)
app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('detail/<int:pk>', user_detail, name='detail'),
    path('change_password/', change_password, name='change_password'),
]

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
# from django.utils.text import slugify
from slugify import slugify
User = get_user_model()
# Create your models here.
class Post(models.Model):
    # author = models.CharField(max_length=50, verbose_name="Author")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Author")
    title = models.CharField(max_length=200, verbose_name="Title")
    text = models.TextField(verbose_name="Post text")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Created at", editable=False)
    image = models.ImageField(upload_to='posts/', null=True, verbose_name='Image')
    slug = models.SlugField(max_length=200, unique=True, editable=False, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Post"           # table name
        verbose_name_plural = "Posts"   # table name plural

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

# class PostForm(forms.Form):
#     author = forms.CharField(max_length=50, label="Author")
#     title = forms.CharField(max_length=200, label="Title")
#     text = forms.CharField(label='Post text', widget=forms.Textarea())

class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        author = kwargs.pop('author', None)
        super(PostForm, self).__init__(*args, **kwargs)
        if author:
            self.fields['author'].initial = author
            self.fields['author'].disabled = True

    class Meta:
        model = Post
        fields = ['author', 'title', 'text', 'image']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from .forms import PostForm
from .models import Post


def root(request):
    return render(request, template_name='blog/index.html')

def index(request):
    return render(request, template_name='blog/index.html')

def about(request):
    context = {
        "name": "Dmitri",
        "lastname": "Gorin",
        "email": "d.gorin@yandex.ru",
        "title": "About site"
    }
    return render(request, template_name='blog/about.html', context=context)


@login_required
def add_post(request):
    if request.method == "GET":
        form = PostForm(author=request.user)
        context = {
            'form': form,
            'title': 'Post adding'
        }
        return render(request, template_name='blog/add_post.html', context=context)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, author=request.user)
        if form.is_valid():
            form.save()

        return index(request)


def post_list(request):
    posts = Post.objects.all().order_by('-created_at')
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Posts',
        'page_obj': page_obj
    }
    return render(request, template_name='blog/posts.html', context=context)


def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)
    context = {
        'title': 'Post information',
        'post': post
    }
    return render(request, template_name='blog/post_detail.html', context=context)


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(data=request.POST, instance=post)
        if form.is_valid():
            form.save()
            return post_list(request)
    else:
        form = PostForm(instance=post)
    context = {
        'form': form,
        'title': 'Edit post'
    }
    return render(request, template_name='blog/post_edit.html', context=context)


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect("blog:post_list")
    return render(request, template_name='blog/post_delete.html', context={'post': post})


def page_not_found(request, exception):
    return render(request, 'blog/404.html', status=404)

def forbidden(request, exception):
    return render(request, 'blog/403.html', status=403)

def server_error(request):
    return render(request, 'blog/500.html', status=500)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>About site html page</h2>
<p>Author - {{name}} {{lastname}}</p>
<p>Email - {{email}}</p>
{% endblock content %}

blog/templates/blog/add_post.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Add a new post</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create a post</button>
</form>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<!--    <link href="{% static 'css/styles.css' %}" rel="stylesheet">-->
</head>
<body style="background-image: url('{% static 'img/background2.png' %}')">

<nav class="nav">
  <a class="nav-link active" aria-current="page" href="#">Active</a>

  {% if not user.is_authenticated %}
  <a class="nav-link" href="{% url 'users:register' %}">Register</a>
  <a class="nav-link" href="{% url 'users:login' %}">Login</a>
  {% endif %}

  {% if user.is_authenticated %}
  <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
  <a class="nav-link" href="{% url 'users:detail' pk=user.pk %}">{{user.username}}</a>
  {% endif %}


</nav>
<hr>
{% block content %}
{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>


<body style="background-image: url('{% static 'img/background2.png' %}')">

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<a href="{% url 'blog:post_list'%}">Posts</a>
{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Delete the post?</h2>
<h3>Information about post # {{post.id}}</h3>
<hr>
<p>Author - {{post.author}}</p>
<p>Title - {{post.title}}</p>
<p>Post text</p>
<p>{{post.text}}</p>

{% if post.image %}
    <img width="300px" height="200px" src="{{post.image.url}}">
{% endif %}

<br>
<p>Created at {{post.created_at}}</p>

<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete post</button>
    <a href="{% url 'blog:post_list' %}">
        <button type="button" class="btn btn-primary">Cancel</button>
    </a>
</form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Information about post # {{post.id}}</h2>
<hr>
<p>Author - {{post.author}}</p>
<p>Title - {{post.title}}</p>
<p>Post text</p>
<p>{{post.text}}</p>

{% if post.image %}
    <img width="300px" height="200px" src="{{post.image.url}}">
{% endif %}

<br>
<p>Created at {{post.created_at}}</p>

<div>
    <a href="{% url 'blog:post_edit' pk=post.id %}" class="btn btn-primary">Edit post</a>
    <form action="{% url 'blog:post_delete' pk=post.id %}" method="get" style="display:inline">
        <button type="submit" class="btn btn-danger">Delete post</button>
    </form>
</div>

{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Edit the post</h2>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Edit the post</button>
</form>
{% endblock content %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>List of posts</h2>
{% for post in page_obj %}
    <h2>{{post.author}}: <a href="{{ post.get_absolute_url }}">{{post.title}}</a></h2>
    <p>{{post.text}}</p>
    <p>{{post.created_at}}</p>
    <br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;First</a>
            <a href="?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} from {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number}}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last&raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}